import pyautogui as pag
import time
import random

print(pag.size())

def autodownloader(num,query):
    time.sleep(2)
    pag.moveTo(110, 155, duration=.2)
    pag.click(110, 155)
    time.sleep(2)
    pag.typewrite(f'{query}')
    pag.typewrite(['enter'])
    pag.moveTo(110, 350, duration=.2)
    
    i = 0
    while i < num:
        print(f'Iteration number: {i}')
        time.sleep(2)
        pag.click(110,350)
        time.sleep(2)
        pag.click(770,475)
        time.sleep(65)
        pag.click(300,200)
        time.sleep(2)
        pag.click(300,260)
        time.sleep(2)
        pag.click(400,30,button='middle')
        time.sleep(2)
        pag.click(85,30)
        time.sleep(3.5)
        pag.click(55,155)
        time.sleep(2)
        pag.moveTo(110,350)
        time.sleep(2)
        pag.scroll(random.randint(-245,-215))
        time.sleep(2)
        i += 1
        iteration = (i/num) *100
        if i < num:
            print(f'You are {iteration}% done. Iteration number: {i} starting now.')
        elif i >= num:
            print(f'You are {iteration}% done.')
    
    time.sleep(5)
    pag.click(110, 155, clicks=3)
    pag.typewrite(['backspace'])
    pag.click(925,30)
    time.sleep(2)
    pag.click(880,1050)
    time.sleep(2)
    pag.click(815,75)
    time.sleep(2)
    pag.click(550,325)
    time.sleep(2)
    pag.click(550,200)
    time.sleep(2)
    pag.click(85,30,button='middle')

autodownloader(20,'Medical Facilities in Georgia')
autodownloader(50,'Medical Facilities in Florida')
autodownloader(50,'Medical Facilities in Alabama')
autodownloader(50,'Medical Facilities in Mississippi')
autodownloader(50,'Medical Facilities in Louisiana')
autodownloader(50,'Medical Facilities in Arkansas')
autodownloader(50,'Medical Facilities in Missouri')
autodownloader(50,'Medical Facilities in Illinois')
autodownloader(50,'Medical Facilities in Indiana')
autodownloader(50,'Medical Facilities in Michigan')
autodownloader(50,'Medical Facilities in Wisconsin')
autodownloader(50,'Medical Facilities in Iowa')
autodownloader(50,'Medical Facilities in Minnesota')
autodownloader(50,'Medical Facilities in North Dakota')
autodownloader(50,'Medical Facilities in South Dakota')
autodownloader(50,'Medical Facilities in Nebraska')
autodownloader(50,'Medical Facilities in Kansas')
autodownloader(50,'Medical Facilities in Oklahoma')
autodownloader(50,'Medical Facilities in Texas')
autodownloader(50,'Medical Facilities in New Mexico')
autodownloader(50,'Medical Facilities in Colorado')
autodownloader(50,'Medical Facilities in Wyoming')
autodownloader(50,'Medical Facilities in Montana')
autodownloader(50,'Medical Facilities in Idaho')
autodownloader(50,'Medical Facilities in Utah')
autodownloader(50,'Medical Facilities in Arizona')
autodownloader(50,'Medical Facilities in Washington')
autodownloader(50,'Medical Facilities in Oregon')
autodownloader(50,'Medical Facilities in Nevada')
autodownloader(50,'Medical Facilities in California')
autodownloader(50,'Medical Facilities in Alaska')
autodownloader(50,'Medical Facilities in Hawaii')
autodownloader(50,'Medical Facilities in Washington DC')